# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 solutions.

# This is a not a c-language project but we use the same environment.
language: c
dist: xenial

# --depth flag is breaking our merge, try disabling it
# NOTE: We may be able to go back to depth=50 in production
git:
    depth: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - tcsh pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev gfortran
    - doxygen graphviz flex bison cmake
    - python-numpy python-netcdf4

jobs:
  include:
    - env: JOB="Code compliance"
      script:
        # Whitespace
        - ./.testing/trailer.py -e TEOS10 -l 120 src config_src
        # API Documentation
        - cd docs && doxygen Doxyfile_nortd
        - grep -v "config_src/solo_driver/coupler_types.F90" doxygen.log | tee doxy_errors
        - test ! -s  doxy_errors

    - env:
        - JOB="Configuration testing"
        - DO_REGRESSION_TESTS=false
        - MKMF_TEMPLATE=linux-ubuntu-xenial-gnu.mk
      script:
        - cd .testing
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - make all
        - echo -en 'travis_fold:end:script.1\\r'
        - echo 'Running tests...' && echo -en 'travis_fold:start:script.2\\r'
        - make test
        - echo -en 'travis_fold:end:script.2\\r'

    # NOTE: Code coverage upload is here to reduce load imbalance
    - if: type = pull_request
      env:
        - JOB="Regression testing"
        - DO_REGRESSION_TESTS=true
        - REPORT_COVERAGE=true
        - MKMF_TEMPLATE=linux-ubuntu-xenial-gnu.mk
        - MOM_TARGET_SLUG=${TRAVIS_REPO_SLUG}
        - MOM_TARGET_LOCAL_BRANCH=${TRAVIS_BRANCH}
      script:
        - cd .testing
        - echo 'Build executables...' && echo -en 'travis_fold:start:script.1\\r'
        - make build.regressions
        - echo -en 'travis_fold:end:script.1\\r'
        - echo 'Running tests...' && echo -en 'travis_fold:start:script.2\\r'
        - make test.regressions
        - echo -en 'travis_fold:end:script.2\\r'
